/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as UserRouteImport } from './routes/user'
import { Route as StartPlantingRouteImport } from './routes/start-planting'
import { Route as SignuppageRouteImport } from './routes/signuppage'
import { Route as PestsRouteImport } from './routes/pests'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginpageRouteImport } from './routes/loginpage'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as ProtectedRouteRouteImport } from './routes/ProtectedRoute'
import { Route as IndexRouteImport } from './routes/index'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const StartPlantingRoute = StartPlantingRouteImport.update({
  id: '/start-planting',
  path: '/start-planting',
  getParentRoute: () => rootRouteImport,
} as any)
const SignuppageRoute = SignuppageRouteImport.update({
  id: '/signuppage',
  path: '/signuppage',
  getParentRoute: () => rootRouteImport,
} as any)
const PestsRoute = PestsRouteImport.update({
  id: '/pests',
  path: '/pests',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginpageRoute = LoginpageRouteImport.update({
  id: '/loginpage',
  path: '/loginpage',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/ProtectedRoute',
  path: '/ProtectedRoute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ProtectedRoute': typeof ProtectedRouteRoute
  '/analysis': typeof AnalysisRoute
  '/crops': typeof CropsRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/loginpage': typeof LoginpageRoute
  '/markets': typeof MarketsRoute
  '/pests': typeof PestsRoute
  '/signuppage': typeof SignuppageRoute
  '/start-planting': typeof StartPlantingRoute
  '/user': typeof UserRoute
  '/weather': typeof WeatherRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ProtectedRoute': typeof ProtectedRouteRoute
  '/analysis': typeof AnalysisRoute
  '/crops': typeof CropsRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/loginpage': typeof LoginpageRoute
  '/markets': typeof MarketsRoute
  '/pests': typeof PestsRoute
  '/signuppage': typeof SignuppageRoute
  '/start-planting': typeof StartPlantingRoute
  '/user': typeof UserRoute
  '/weather': typeof WeatherRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ProtectedRoute': typeof ProtectedRouteRoute
  '/analysis': typeof AnalysisRoute
  '/crops': typeof CropsRoute
  '/home': typeof HomeRoute
  '/insights': typeof InsightsRoute
  '/loginpage': typeof LoginpageRoute
  '/markets': typeof MarketsRoute
  '/pests': typeof PestsRoute
  '/signuppage': typeof SignuppageRoute
  '/start-planting': typeof StartPlantingRoute
  '/user': typeof UserRoute
  '/weather': typeof WeatherRoute
  '/zones': typeof ZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ProtectedRoute'
    | '/analysis'
    | '/crops'
    | '/home'
    | '/insights'
    | '/loginpage'
    | '/markets'
    | '/pests'
    | '/signuppage'
    | '/start-planting'
    | '/user'
    | '/weather'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ProtectedRoute'
    | '/analysis'
    | '/crops'
    | '/home'
    | '/insights'
    | '/loginpage'
    | '/markets'
    | '/pests'
    | '/signuppage'
    | '/start-planting'
    | '/user'
    | '/weather'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/ProtectedRoute'
    | '/analysis'
    | '/crops'
    | '/home'
    | '/insights'
    | '/loginpage'
    | '/markets'
    | '/pests'
    | '/signuppage'
    | '/start-planting'
    | '/user'
    | '/weather'
    | '/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRoute
  AnalysisRoute: typeof AnalysisRoute
  CropsRoute: typeof CropsRoute
  HomeRoute: typeof HomeRoute
  InsightsRoute: typeof InsightsRoute
  LoginpageRoute: typeof LoginpageRoute
  MarketsRoute: typeof MarketsRoute
  PestsRoute: typeof PestsRoute
  SignuppageRoute: typeof SignuppageRoute
  StartPlantingRoute: typeof StartPlantingRoute
  UserRoute: typeof UserRoute
  WeatherRoute: typeof WeatherRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-planting': {
      id: '/start-planting'
      path: '/start-planting'
      fullPath: '/start-planting'
      preLoaderRoute: typeof StartPlantingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signuppage': {
      id: '/signuppage'
      path: '/signuppage'
      fullPath: '/signuppage'
      preLoaderRoute: typeof SignuppageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pests': {
      id: '/pests'
      path: '/pests'
      fullPath: '/pests'
      preLoaderRoute: typeof PestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loginpage': {
      id: '/loginpage'
      path: '/loginpage'
      fullPath: '/loginpage'
      preLoaderRoute: typeof LoginpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ProtectedRoute': {
      id: '/ProtectedRoute'
      path: '/ProtectedRoute'
      fullPath: '/ProtectedRoute'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRoute,
  AnalysisRoute: AnalysisRoute,
  CropsRoute: CropsRoute,
  HomeRoute: HomeRoute,
  InsightsRoute: InsightsRoute,
  LoginpageRoute: LoginpageRoute,
  MarketsRoute: MarketsRoute,
  PestsRoute: PestsRoute,
  SignuppageRoute: SignuppageRoute,
  StartPlantingRoute: StartPlantingRoute,
  UserRoute: UserRoute,
  WeatherRoute: WeatherRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
